-- ============================================================
-- 033 — CHECKOUT IDEMPOTENCY TOKEN
--
-- Makes the DATABASE the final authority on "is this the same checkout
-- attempt", instead of the application guessing from phone + total inside a
-- 90-second window.
--
-- Why this is needed, measured on 30 days of live data:
--   duplicates by gap    <90s: 0    90s-5m: 30    5-30m: 8
--                        30m-2h: 3   2-6h: 8      6-24h: 16
-- Zero under 90s proves the existing app-level guard works perfectly inside
-- its range. 30 of 65 duplicates land in the 3.5-minute blind spot that opens
-- the moment it closes — a customer whose submit appeared to fail, retrying.
--
-- Widening that window is NOT the fix. Its key (phone + total) is a guess: at
-- two hours it would swallow a genuine second order and hand the customer a
-- success for an order that was never created. A token cannot do that. Two
-- visits produce two tokens and two orders; one visit submitted twenty times
-- produces one order and twenty identical successes.
--
-- SAFETY PROPERTIES (each one deliberate):
--   · Column is NULLABLE with no default, so every existing row stays valid
--     and untouched. This migration writes to no existing row.
--   · The index is PARTIAL on checkout_token IS NOT NULL. Postgres treats
--     NULLs as distinct anyway, but stating it keeps legacy rows out of the
--     index entirely rather than relying on that.
--   · Scoped to (store_id, checkout_token): stores can never collide with one
--     another, even if two clients ever generated the same token.
--   · Abandoned drafts are EXCLUDED. Drafts live in this same table, so if a
--     draft ever carried the token of the checkout that later converted, the
--     real order would hit a unique violation and the customer would lose
--     their order. Excluding them makes that impossible by construction —
--     the merchant's rule is that an abandoned record must never block a real
--     order.
--   · There is NO uniqueness on phone, on (phone, product), and no
--     time-based restriction. A customer may order again whenever they like;
--     they simply get a new token when they start a new checkout.
--
-- Rollback is a single DROP INDEX; the column can stay harmlessly.
-- ============================================================

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS checkout_token TEXT;

COMMENT ON COLUMN orders.checkout_token IS
  'Opaque per-checkout-attempt id generated by the client when the checkout '
  'form mounts. Stable for the whole attempt, so a retry carries the same '
  'value and resolves to the same order. NULL on legacy rows and on abandoned '
  'drafts.';

-- The actual protection. Everything above is bookkeeping; this line is what
-- makes a concurrent double-submit impossible rather than merely unlikely.
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_store_checkout_token
  ON orders (store_id, checkout_token)
  WHERE checkout_token IS NOT NULL
    AND status <> 'abandoned';

-- Lookup path for the fast route: the API checks for an existing order by
-- token before attempting the insert, so the common retry never reaches the
-- error path at all.
CREATE INDEX IF NOT EXISTS idx_orders_checkout_token_lookup
  ON orders (store_id, checkout_token)
  WHERE checkout_token IS NOT NULL;
